/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness/readiness probe.
         * @description Reports whether the Control Plane is able to serve requests. Intended for
         *     load balancers and orchestrators. Public and unauthenticated; it MUST NOT
         *     disclose any identity, node, or policy information.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Component and protocol version metadata.
         * @description Returns the Control Plane component name, its build version (SemVer), and
         *     the protocol version ranges it speaks on the CP<->Gateway gRPC plane and
         *     the Agent<->Gateway wire protocol. Public and unauthenticated.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * RFC 9457 Problem Details
         * @description Problem details for HTTP APIs as defined by RFC 9457 (obsoletes RFC 7807).
         *     Error responses use media type `application/problem+json`.
         */
        ProblemDetails: {
            /**
             * Format: uri-reference
             * @description A URI reference identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description A short, human-readable summary of the problem type. */
            title?: string;
            /**
             * Format: int32
             * @description The HTTP status code.
             */
            status?: number;
            /** @description A human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description A URI reference identifying the specific occurrence.
             */
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Health Status
         * @description Liveness/readiness result, loosely modelled on the IETF health-check draft.
         */
        HealthStatus: {
            /**
             * @description Overall health indicator.
             * @enum {string}
             */
            status: "pass" | "fail" | "warn";
        };
        /**
         * Protocol Version Range
         * @description An inclusive range of supported protocol versions, `major.minor` strings.
         */
        ProtocolVersionRange: {
            /** @description Inclusive lowest supported protocol version, e.g. "1.0". */
            min: string;
            /** @description Inclusive highest supported protocol version, e.g. "1.0". */
            max: string;
        };
        /**
         * Version Info
         * @description Component build version and the protocol ranges it negotiates.
         */
        VersionInfo: {
            /** @description Formal component name. */
            component: string;
            /** @description Component build version (SemVer 2.0.0). */
            version: string;
            /**
             * Protocol Ranges
             * @description Supported protocol version ranges by plane.
             */
            protocols: {
                controlPlaneGatewayGrpc: components["schemas"]["ProtocolVersionRange"];
                agentGatewayWire: components["schemas"]["ProtocolVersionRange"];
            };
        };
    };
    responses: {
        /** @description An error occurred. The body is an RFC 9457 problem document. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Control Plane is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description The Control Plane is not ready to serve requests. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
